config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Admin routes

  namespace :admin do
    resources :users

    resources :artists

    resources :artists_tags

    resources :artworks

    resources :artworks_tags

    resources :blogs

    resources :blogs_tags

    resources :clients

    resources :companies

    resources :projects

    resources :projects_tags

    resources :tags

    root to: 'users#index'
  end

  # Blogs routes

  resources :blogs, only: %i[index show], path: 'blog'

  # Devise routes

  devise_for :users

  # Projects routes

  resources :projects

  # Tags routes

  resources :tags

  # Artworks routes

  resources :artworks

  # Artists routes

  resources :artists

  # Companies routes

  resources :companies

  # Clients routes

  resources :clients

  # Statics routes

  root 'statics#show', page: 'home'

  get '/:page', to: 'statics#show'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
# frozen_string_literal: true

class Artist < ApplicationRecord
  searchkick

  extend FriendlyId

  friendly_id :full_name, use: :slugged

  has_one_attached :avatar

  has_many :artworks

  has_many :artists_tags, dependent: :destroy

  has_many :tags, through: :artists_tags

  has_many :projects, dependent: :destroy

  has_many :clients, through: :projects

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/artists_tag.rb
# frozen_string_literal: true

class ArtistsTag < ApplicationRecord
  belongs_to :artist
  belongs_to :tag
end

app/models/artwork.rb
# frozen_string_literal: true

class Artwork < ApplicationRecord
  searchkick

  extend FriendlyId

  friendly_id :title, use: :slugged

  belongs_to :artist

  has_many_attached :images

  has_many :artworks_tags, dependent: :destroy

  has_many :tags, through: :artworks_tags
end

app/models/artworks_tag.rb
# frozen_string_literal: true

class ArtworksTag < ApplicationRecord
  belongs_to :artwork
  belongs_to :tag
end

app/models/blog.rb
# frozen_string_literal: true

class Blog < ApplicationRecord
  searchkick

  extend FriendlyId

  friendly_id :title, use: :slugged

  has_rich_text :body

  has_one_attached :cover

  belongs_to :user

  has_many :blogs_tags, dependent: :destroy

  has_many :tags, through: :blogs_tags
end

app/models/blogs_tag.rb
# frozen_string_literal: true

class BlogsTag < ApplicationRecord
  belongs_to :blog
  belongs_to :tag
end

app/models/client.rb
# frozen_string_literal: true

class Client < ApplicationRecord
  searchkick
  extend FriendlyId
  friendly_id :full_name, use: :slugged
  belongs_to :company, optional: true
  has_one_attached :avatar

  has_many :projects, dependent: :destroy
  has_many :artists, through: :projects

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/company.rb
# frozen_string_literal: true

class Company < ApplicationRecord
  searchkick
  extend FriendlyId
  friendly_id :name, use: :slugged
  has_many :clients
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord

  searchkick

  belongs_to :artist

  belongs_to :client

  has_many :projects_tags, dependent: :destroy

  has_many :tags, through: :projects_tags
end

app/models/projects_tag.rb
# frozen_string_literal: true

class ProjectsTag < ApplicationRecord
  belongs_to :project
  belongs_to :tag
end

app/models/tag.rb
# frozen_string_literal: true

class Tag < ApplicationRecord
  searchkick
  extend FriendlyId
  friendly_id :title, use: :slugged
  has_many :projects_tags, dependent: :destroy
  has_many :projects, through: :projects_tags
  has_many :blogs_tags, dependent: :destroy
  has_many :blogs, through: :blogs_tags
  has_many :artists_tags, dependent: :destroy
  has_many :artists, through: :artists_tags
  has_many :artworks_tags, dependent: :destroy
  has_many :artworks, through: :artworks_tags
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  extend FriendlyId
  friendly_id :full_name, use: :slugged
  has_one_attached :avatar

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :blogs

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/admin/artists_controller.rb
# frozen_string_literal: true

module Admin
  class ArtistsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   foo = Foo.find(params[:id])
    #   foo.update(params[:foo])
    #   send_foo_updated_email
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    def find_resource(param)
      Artist.find_by!(slug: param)
    end

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #  if current_user.super_admin?
    #    resource_class
    #  else
    #    resource_class.with_less_stuff
    #  end
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/artists_controller.rb
# frozen_string_literal: true

class ArtistsController < ApplicationController
  layout '_navbar'

  before_action :set_artist, only: %i[show edit update destroy]

  respond_to :js, :html, :json

  # GET /artists

  # GET /artists.json

  def index
    search = params[:search].present? ? params[:search] : nil

    @artists = if search

                 # Render search results

                 Artist.search(params[:search], page: params[:page], per_page: 20)

               else

                 # Render blog articles

                 Artist.all.order(created_at: :desc).page(params[:page])

               end
  end

  # GET /artists/1

  # GET /artists/1.json

  def show; end

  # GET /artists/new

  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit

  def edit; end

  # POST /artists

  # POST /artists.json

  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save

        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }

        format.json { render :show, status: :created, location: @artist }

      else

        format.html { render :new }

        format.json { render json: @artist.errors, status: :unprocessable_entity }

      end
    end
  end

  # PATCH/PUT /artists/1

  # PATCH/PUT /artists/1.json

  def update
    respond_to do |format|
      if @artist.update(artist_params)

        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }

        format.json { render :show, status: :ok, location: @artist }

      else

        format.html { render :edit }

        format.json { render json: @artist.errors, status: :unprocessable_entity }

      end
    end
  end

  # DELETE /artists/1

  # DELETE /artists/1.json

  def destroy
    @artist.destroy

    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }

      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.

  def set_artist
    @artist = Artist.friendly.find(params[:id])
  end

  # Only allow a list of trusted parameters through.

  def artist_params
    params.fetch(:artist, {})
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/artworks_helper.rb
module ArtworksHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/artists/_artist.html.erb
<%= link_to artist_path(artist.id), :class => 'index-artist-ctn' do %>
  <%= image_tag("img.png", alt: "art-zeppelin-index-artist-portrait", class: "")%>
  <div class="index-artist-text-ctn">
    <div>
      <h3 class="index-artist-name"><%= artist.first_name + " " + artist.last_name %></h3>
      <hr class="index-artist-hr">
      <p class="index-artist-description"><%= artist.description %></p>
    </div>
    <div class="index-artist-tag-ctn">
      <% artist.tags.each do |tag| %>
        <p class="index-artist-tag"><%= tag.title %></p>
      <% end %>
    </div>
  </div>
  <div class="index-artist-fill-ctn"></div>
<% end %>

app/views/artists/_form.html.erb
<%= form_with(model: artist, local: true) do |form| %>
  <% if artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
        <% artist.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/artists/_search.html.erb
<%# Search form %>
<%= form_tag(artists_path, method: 'get', class: 'form-inline input-text-btn-ctn', role: 'search') do %>
  <div class="form-group text">
    <%# Search field %>
    <%= text_field_tag :search, nil, placeholder: "Rechercher un article", class: "form-control", name: "search", autocomplete: :off %>
  </div>
  <%# Submit button %>
  <%= submit_tag '', class: 'btn btn-primary', value: 'Rechercher' %>
<% end %>

app/views/artists/index.html.erb
<div class="index-artist-section-1">
  <h1>Découvrir nos <span class="span-orange">artiste</span></h1>
  <div class="crsl-ctn">
    <div class="crsl-all-img-ctn">
      <div class="crsl-img-ctn">
        <%= image_tag("img.png", alt: "art-zeppelin-index-artist-artwork", class: "crsl-img") %>
      </div>
      <div class="crsl-img-ctn">
        <%= image_tag("img.png", alt: "art-zeppelin-index-artist-artwork", class: "crsl-img") %>
      </div>
      <div class="crsl-img-ctn">
        <%= image_tag("img.png", alt: "art-zeppelin-index-artist-artwork", class: "crsl-img") %>
      </div>
      <div class="crsl-img-ctn">
        <%= image_tag("img.png", alt: "art-zeppelin-index-artist-artwork", class: "crsl-img") %>
      </div>
    </div>
    <div class="crsl-controls">
      <svg class="crsl-prev" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="36" height="35" viewBox="0 0 36 35">
        <defs>
          <clipPath id="clip-Index_8">
            <rect width="36" height="35"/>
          </clipPath>
        </defs>
        <g id="Index_8" data-name="Index – 8" clip-path="url(#clip-Index_8)">
          <rect width="36" height="35" fill="#fff"/>
          <g id="Groupe_614" data-name="Groupe 614" transform="translate(-5817.75 -6010)">
            <rect id="Rectangle_228" data-name="Rectangle 228" width="36" height="35" transform="translate(5817.75 6010)" fill="#fa4616"/>
            <path id="Tracé_1157" data-name="Tracé 1157" d="M0,0,8.86,8.86,0,17.72" transform="translate(5839.361 6036.632) rotate(180)" fill="none" stroke="#fff" stroke-width="3"/>
          </g>
        </g>
      </svg>
      <svg class="crsl-next" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="36" height="35" viewBox="0 0 36 35">
        <defs>
          <clipPath id="clip-Index_9">
            <rect width="36" height="35"/>
          </clipPath>
        </defs>
        <g id="Index_9" data-name="Index – 9" clip-path="url(#clip-Index_9)">
          <rect width="36" height="35" fill="#fff"/>
          <g id="Groupe_614" data-name="Groupe 614" transform="translate(-5817.75 -6010)">
            <rect id="Rectangle_228" data-name="Rectangle 228" width="36" height="35" transform="translate(5817.75 6010)" fill="#fa4616"/>
            <path id="Tracé_1157" data-name="Tracé 1157" d="M0,0,8.86,8.86,0,17.72" transform="translate(5832.5 6018.912)" fill="none" stroke="#fff" stroke-width="3"/>
          </g>
        </g>
      </svg>
    </div>
  </div>
  <%= image_tag("img-artist.png", alt: "art-zeppelin-index-artist-artwork-illustration", class: "index-artist-illu")%>
</div>
<div class="section index-artist-section-2">
  <div class="index-artist-section-2-filters-ctn">
    <div class="index-artist-section-2-filters-btn-ctn">
      <a href="#" class="filter-btn">Tableau</a>
      <a href="#" class="filter-btn">Fresque</a>
      <a href="#" class="filter-btn">Sculpture</a>
      <a href="#" class="filter-btn">Performance</a>
    </div>
    <%= render 'search' %>
  </div>
</div>
<div class="section index-artist-section-3" id="artists">
  <%= render @artists %>
</div>
<% if @artists.count > 5 %>
  <div class="card">
    <div class="card-body d-flex justify-content-center" id="paginate">
      <%= paginate @artists, remote: true %>
    </div>
  </div>
<% end %>
<script class="carousel">
  const crslNextBtn = document.querySelector('.crsl-next');
  const crslPrevBtn = document.querySelector('.crsl-prev');
  const crslAllImgs = document.querySelector('.crsl-all-img-ctn');
  const crslImgs = document.querySelectorAll('.crsl-img');
  const crslImgsLength = document.querySelectorAll('.crsl-img').length;
  var nextCount = 0;
  
  crslImgs[nextCount+1].classList.add('crsl-img-active');
  
  function crslPrevImg() {
      nextCount -= 1;
      if (nextCount < -1) {
          nextCount = crslImgsLength - 2;
      }
      crslAllImgs.style.transform = `translateX(${nextCount*50*-1}vw)`;
      if (nextCount > -1) crslImgs[nextCount].classList.remove('crsl-img-active');
      crslImgs[nextCount+1].classList.add('crsl-img-active');
      if (nextCount < crslImgsLength - 1) crslImgs[nextCount + 2].classList.remove('crsl-img-active');
  }
  function crslNextImg() {
      nextCount += 1;
      if (nextCount > crslImgsLength - 2) {
          nextCount = -1;
      }
  
      crslAllImgs.style.transform = `translateX(${nextCount*50*-1}vw)`;
      if (nextCount > -1) crslImgs[nextCount].classList.remove('crsl-img-active');
      crslImgs[nextCount+1].classList.add('crsl-img-active');
      if (nextCount < crslImgsLength - 1) crslImgs[nextCount + 2].classList.remove('crsl-img-active');
  }
  crslPrevBtn.addEventListener('click', crslPrevImg);
  crslNextBtn.addEventListener('click', crslNextImg);
</script>

app/views/artists/index.js.erb
$("#artists").html("<%= j render(@artists) %>");
$("#paginate").html("<%= escape_javascript(paginate(@artists, remote: true)) %>");
$(document).ready(function(){
$(this).scrollTop(0);
});

app/views/artists/show.html.erb
<div class="section show-artist-section-1">
  <%= image_tag(@artist.avatar, alt: "artist-portrait") %>
  <div class="show-artist-section-1-text-ctn">
    <h2><%= @artist.first_name + " " + @artist.last_name %></h2>
    <hr>
    <p class="show-artist-description"><%= @artist.description %></p>
    <div class="show-artist-tags-ctn">
      <% @artist.tags.each do |tag| %>
        <p class="tag"><%= tag.title %></p>
      <% end %>
    </div>
    <%= link_to "Réserver cet artiste", "contact"%>
  </div>
</div>
<div class="section show-artist-section-2">
  <% @artist.artworks.each do |artwork| %>
    <% artwork.images.each do |artworkImage| %>
      <%= image_tag(artworkImage, alt: "", class: "show-artist-artwork") %>
    <% end %>
  <% end %>
</div>
<div class="lightbox-ctn">
  <div class="crsl-ctn">
    <div class="crsl-all-img-ctn-2">
      <% @artist.artworks.last(20).each do |artwork| %>
        <% artwork.images.each do |artworkImage| %>
          <div class="crsl-img-ctn">
            <div class="crsl-img-2">
              <%= image_tag(artworkImage, alt: "") %>
              <p><%= artwork.artist.first_name + " " + artwork.artist.last_name + " - " + artwork.title %></p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="crsl-controls">
      <svg class="crsl-prev-2" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="36" height="35" viewBox="0 0 36 35">
        <defs>
          <clipPath id="clip-Index_8">
            <rect width="36" height="35"/>
          </clipPath>
        </defs>
        <g id="Index_8" data-name="Index – 8" clip-path="url(#clip-Index_8)">
          <rect width="36" height="35" fill="#fff"/>
          <g id="Groupe_614" data-name="Groupe 614" transform="translate(-5817.75 -6010)">
            <rect id="Rectangle_228" data-name="Rectangle 228" width="36" height="35" transform="translate(5817.75 6010)" fill="#fa4616"/>
            <path id="Tracé_1157" data-name="Tracé 1157" d="M0,0,8.86,8.86,0,17.72" transform="translate(5839.361 6036.632) rotate(180)" fill="none" stroke="#fff" stroke-width="3"/>
          </g>
        </g>
      </svg>
      <svg class="crsl-next-2" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="36" height="35" viewBox="0 0 36 35">
        <defs>
          <clipPath id="clip-Index_9">
            <rect width="36" height="35"/>
          </clipPath>
        </defs>
        <g id="Index_9" data-name="Index – 9" clip-path="url(#clip-Index_9)">
          <rect width="36" height="35" fill="#fff"/>
          <g id="Groupe_614" data-name="Groupe 614" transform="translate(-5817.75 -6010)">
            <rect id="Rectangle_228" data-name="Rectangle 228" width="36" height="35" transform="translate(5817.75 6010)" fill="#fa4616"/>
            <path id="Tracé_1157" data-name="Tracé 1157" d="M0,0,8.86,8.86,0,17.72" transform="translate(5832.5 6018.912)" fill="none" stroke="#fff" stroke-width="3"/>
          </g>
        </g>
      </svg>
    </div>
    <%= image_tag("icons/close.svg", alt: "", class: "lightbox-close") %>
  </div>
  <script class="carousel-2">
    const crslNextBtn2 = document.querySelector('.crsl-next-2');
    const crslPrevBtn2 = document.querySelector('.crsl-prev-2');
    const crslAllImgs2 = document.querySelector('.crsl-all-img-ctn-2');
    const crslImgs2 = document.querySelectorAll('.crsl-img-2');
    const crslImgsLength2 = document.querySelectorAll('.crsl-img-2').length;
    var nextCount2 = 0;
    
        if(crslImgs2.length < 2) {crslImgs2[nextCount2].classList.add('crsl-img-active-2')}
        else {crslImgs2[nextCount2+1].classList.add('crsl-img-active-2')};
    
    function crslPrevImg() {
        nextCount2 -= 1;
        if (nextCount2 < -1) {
            nextCount2 = crslImgsLength2 - 2;
        }
        crslAllImgs2.style.transform = `translateX(${nextCount2*50*-1}vw)`;
        if (nextCount2 > -1) crslImgs2[nextCount2].classList.remove('crsl-img-active-2');
        crslImgs2[nextCount2+1].classList.add('crsl-img-active-2');
        if (nextCount < crslImgsLength2 - 1) crslImgs2[nextCount + 2].classList.remove('crsl-img-active-2');
    }
    function crslNextImg() {
        nextCount2 += 1;
        if (nextCount2 > crslImgsLength2 - 2) {
            nextCount2 = -1;
        }
    
        crslAllImgs2.style.transform = `translateX(${nextCount2*50*-1}vw)`;
        if (nextCount2 > -1) crslImgs2[nextCount2].classList.remove('crsl-img-active-2');
        crslImgs2[nextCount2+1].classList.add('crsl-img-active-2');
        if (nextCount2 < crslImgsLength2 - 1) crslImgs2[nextCount2 + 2].classList.remove('crsl-img-active-2');
    }
    crslPrevBtn2.addEventListener('click', crslPrevImg);
    crslNextBtn2.addEventListener('click', crslNextImg);
    
    /* Open right image */
    const lightboxCtn = document.querySelector('.lightbox-ctn');
    const allIndexArtworks = document.querySelectorAll('.show-artist-artwork');
    
    function openLightbox(index) {
        lightboxCtn.style.display = "flex";
        nextCount2 = index-1;
        crslAllImgs2.style.transform = `translateX(${nextCount2*50*-1}vw)`;
        if(crslImgs2.length < 2) {crslImgs2[nextCount2].classList.add('crsl-img-active-2')}
        else {crslImgs2[nextCount2+1].classList.add('crsl-img-active-2')};
    }
    
    for (let i = 0; i < allIndexArtworks.length; i++) {
    allIndexArtworks[i].addEventListener('click', function() {openLightbox(i)},false);
    }
    
    /* Close lightbox */
    const closeLightboxBtn = document.querySelector('.lightbox-close');
    
    closeLightboxBtn.addEventListener('click', function(e) {
        lightboxCtn.style.display = "none";
    });
  </script>