config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Admin routes

  namespace :admin do
    resources :users

    resources :artists

    resources :artists_tags

    resources :artworks

    resources :artworks_tags

    resources :blogs

    resources :blogs_tags

    resources :clients

    resources :companies

    resources :projects

    resources :projects_tags

    resources :tags

    root to: 'users#index'
  end

  # Blogs routes

  resources :blogs, only: %i[index show], path: 'blog'

  # Devise routes

  devise_for :users

  # Projects routes

  resources :projects

  # Tags routes

  resources :tags

  # Artworks routes

  resources :artworks

  # Artists routes

  resources :artists

  # Companies routes

  resources :companies

  # Clients routes

  resources :clients

  # Statics routes

  root 'statics#show', page: 'home'

  get '/:page', to: 'statics#show'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/artist.rb
# frozen_string_literal: true

class Artist < ApplicationRecord
  searchkick

  extend FriendlyId

  friendly_id :full_name, use: :slugged

  has_one_attached :avatar

  has_many :artworks

  has_many :artists_tags, dependent: :destroy

  has_many :tags, through: :artists_tags

  has_many :projects, dependent: :destroy

  has_many :clients, through: :projects

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/artists_tag.rb
# frozen_string_literal: true

class ArtistsTag < ApplicationRecord
  belongs_to :artist
  belongs_to :tag
end

app/models/artwork.rb
# frozen_string_literal: true

class Artwork < ApplicationRecord
  searchkick

  extend FriendlyId

  friendly_id :title, use: :slugged

  belongs_to :artist

  has_many_attached :images

  has_many :artworks_tags, dependent: :destroy

  has_many :tags, through: :artworks_tags
end

app/models/artworks_tag.rb
# frozen_string_literal: true

class ArtworksTag < ApplicationRecord
  belongs_to :artwork
  belongs_to :tag
end

app/models/blog.rb
# frozen_string_literal: true

class Blog < ApplicationRecord
  searchkick

  extend FriendlyId

  friendly_id :title, use: :slugged

  has_rich_text :body

  has_one_attached :cover

  belongs_to :user

  has_many :blogs_tags, dependent: :destroy

  has_many :tags, through: :blogs_tags
end

app/models/blogs_tag.rb
# frozen_string_literal: true

class BlogsTag < ApplicationRecord
  belongs_to :blog
  belongs_to :tag
end

app/models/client.rb
# frozen_string_literal: true

class Client < ApplicationRecord
  searchkick
  extend FriendlyId
  friendly_id :full_name, use: :slugged
  belongs_to :company, optional: true
  has_one_attached :avatar

  has_many :projects, dependent: :destroy
  has_many :artists, through: :projects

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/company.rb
# frozen_string_literal: true

class Company < ApplicationRecord
  searchkick
  extend FriendlyId
  friendly_id :name, use: :slugged
  has_many :clients
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord

  searchkick

  belongs_to :artist

  belongs_to :client

  has_many :projects_tags, dependent: :destroy

  has_many :tags, through: :projects_tags
end

app/models/projects_tag.rb
# frozen_string_literal: true

class ProjectsTag < ApplicationRecord
  belongs_to :project
  belongs_to :tag
end

app/models/tag.rb
# frozen_string_literal: true

class Tag < ApplicationRecord
  searchkick
  extend FriendlyId
  friendly_id :title, use: :slugged
  has_many :projects_tags, dependent: :destroy
  has_many :projects, through: :projects_tags
  has_many :blogs_tags, dependent: :destroy
  has_many :blogs, through: :blogs_tags
  has_many :artists_tags, dependent: :destroy
  has_many :artists, through: :artists_tags
  has_many :artworks_tags, dependent: :destroy
  has_many :artworks, through: :artworks_tags
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  extend FriendlyId
  friendly_id :full_name, use: :slugged
  has_one_attached :avatar

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :blogs

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/statics_controller.rb
# frozen_string_literal: true

class StaticsController < ApplicationController
  layout '_navbar'

  def show
    @client = Client.new

    if valid_page?

      render template: params[:page].to_s

    else

      render page: '/public/404', status: :not_found

    end
  end

  private

  def valid_page?
    File.exist?(
      Pathname.new(
        Rails.root + "app/views/statics/#{params[:page]}.html.erb"
      )
    )
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/artworks_helper.rb
module ArtworksHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/statics/deductions.html.erb
<div class="page-title-ctn">
    <img src="https://images.pexels.com/photos/3047316/pexels-photo-3047316.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260" alt="" class="page-title-img">
    <h1 class="h1-page-title">Investir dans l’art, c’est s’engager pour la culture</h1>
</div>

<div class="main">
    <h4 class="deductions-intro">En France, les entreprises bénéficient pour ce faire d’avantages fiscaux. L’acquisition d’oeuvres originales, d’artistes vivants, peut être déduite du résultat de l’exercice d’acquisition et des quatre années suivantes, par fractions égales, une somme égale au prix d’acquisition (sous réserve que l’oeuvre soit exposée à la vue des salariés ou du public).</h4>
    <p class="deductions-details">Retrouvez tout le détail en cliquant sur l’article 238 bis AB: Article 238 bis AB Modifié par Loi n°2005-1720 du 30 décembre 2005 – art. 70 JORF 31 décembre 2005</p>
    <p class="deductions-text">Les entreprises qui achètent, à compter du 1er janvier 2002, des oeuvres originales d’artistes vivants et les inscrivent à un compte d’actif immobilisé peuvent déduire du résultat de l’exercice d’acquisition et des quatre années suivantes, par fractions égales, une somme égale au prix d’acquisition. La déduction ainsi effectuée au titre de chaque exercice ne peut excéder la limite mentionnée au premier alinéa du 1 de l’article 238 bis, minorée du total des versements mentionnés au même article. Pour bénéficier de la déduction prévue au premier alinéa, l’entreprise doit exposer dans un lieu accessible au public ou aux salariés, à l’exception de leurs bureaux, le bien qu’elle a acquis pour la période correspondant à l’exercice d’acquisition et aux quatre années suivantes. L’entreprise doit inscrire à un compte de réserve spéciale au passif du bilan une somme égale à la déduction opérée en application du premier alinéa. Cette somme est réintégrée au résultat imposable en cas de changement d’affectation ou de cession de l’oeuvre ou de l’instrument ou de prélèvement sur le compte de réserve. L’entreprise peut constituer une provision pour dépréciation lorsque la dépréciation de l’oeuvre excède le montant des déductions déjà opérées au titre des premier à quatrième alinéas.</p>
    <%= link_to "Lien vers l’article 238 bis AB", "https://www.legifrance.gouv.fr/affichCodeArticle.do?idArticle=LEGIARTI000006303974&cidTexte=LEGITEXT000006069577", :class => "deductions-link"%>
    <p class="deductions-contact-1">Vous avez une question sur les démarches à suivre ?</p>
    <p class="deductions-contact-2">Nous sommes à votre disposition: contact@artzeppelin.com</p>
</div>

app/views/statics/for_artists.html.erb
<div class="for-artists-section-1">
  <h1>Vous êtes un <span class="span-orange">artiste</span> ?</h1>
  <div class="crsl-ctn">
    <div class="crsl-all-img-ctn">
      <div class="crsl-img-ctn">
        <%= image_tag("for-panels-7.png", alt: "art-zeppelin-index-artist-artwork", class: "crsl-img") %>
      </div>
      <div class="crsl-img-ctn">
        <%= image_tag("for-panels-1.png", alt: "art-zeppelin-index-artist-artwork", class: "crsl-img") %>
      </div>
      <div class="crsl-img-ctn">
        <%= image_tag("for-panels-2.png", alt: "art-zeppelin-index-artist-artwork", class: "crsl-img") %>
      </div>
      <div class="crsl-img-ctn">
        <%= image_tag("for-panels-3.png", alt: "art-zeppelin-index-artist-artwork", class: "crsl-img") %>
      </div>
    </div>
    <div class="crsl-controls">
      <svg class="crsl-prev" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="36" height="35" viewBox="0 0 36 35">
        <defs>
          <clipPath id="clip-Index_8">
            <rect width="36" height="35"/>
          </clipPath>
        </defs>
        <g id="Index_8" data-name="Index – 8" clip-path="url(#clip-Index_8)">
          <rect width="36" height="35" fill="#fff"/>
          <g id="Groupe_614" data-name="Groupe 614" transform="translate(-5817.75 -6010)">
            <rect id="Rectangle_228" data-name="Rectangle 228" width="36" height="35" transform="translate(5817.75 6010)" fill="#fa4616"/>
            <path id="Tracé_1157" data-name="Tracé 1157" d="M0,0,8.86,8.86,0,17.72" transform="translate(5839.361 6036.632) rotate(180)" fill="none" stroke="#fff" stroke-width="3"/>
          </g>
        </g>
      </svg>
      <svg class="crsl-next" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="36" height="35" viewBox="0 0 36 35">
        <defs>
          <clipPath id="clip-Index_9">
            <rect width="36" height="35"/>
          </clipPath>
        </defs>
        <g id="Index_9" data-name="Index – 9" clip-path="url(#clip-Index_9)">
          <rect width="36" height="35" fill="#fff"/>
          <g id="Groupe_614" data-name="Groupe 614" transform="translate(-5817.75 -6010)">
            <rect id="Rectangle_228" data-name="Rectangle 228" width="36" height="35" transform="translate(5817.75 6010)" fill="#fa4616"/>
            <path id="Tracé_1157" data-name="Tracé 1157" d="M0,0,8.86,8.86,0,17.72" transform="translate(5832.5 6018.912)" fill="none" stroke="#fff" stroke-width="3"/>
          </g>
        </g>
      </svg>
    </div>
  </div>
  <%= image_tag("img-for-artists.png", alt: "art-zeppelin-index-artist-artwork-illustration")%>
</div>
<div class="section for-artists-section-2">
  <div class="for-artists-section-2-pictos-ctn">
    <div>
      <%= image_tag("icons/for-icon-1.svg", alt: "art-zeppelin-index-artist-artwork-illustration", class: "for-icons")%>
      <h3>Nous vous proposons<br>
        un projet</h3>
    </div>
    <div>
      <%= image_tag("icons/for-icon-2.svg", alt: "art-zeppelin-index-artist-artwork-illustration", class: "for-icons")%>
      <h3>Vous créez<br>
        une proposition</h3>
    </div>
    <div>
      <%= image_tag("icons/for-icon-3.svg", alt: "art-zeppelin-index-artist-artwork-illustration", class: "for-icons")%>
      <h3>Validation<br>
        de la maquette</h3>
    </div>
    <div>
      <%= image_tag("icons/for-icon-4.svg", alt: "art-zeppelin-index-artist-artwork-illustration", class: "for-icons")%>
      <h3>Vous réalisez<br>
        l’oeuvre</h3>
    </div>
  </div>
</div>
<div class="section for-artists-section-3">
  <h2>Nos modes <span class="span-orange">opératoires</span></h2>
  <div class="for-artists-section-3-insitu-ctn">
    <%= image_tag("in-situ.jpg", alt: "in-situ")%>
    <div class="for-artists-section-3-insitu-text-ctn">
      <h3>In-<span class="span-orange">situ</span></h3>
      <p class="p-bold">Accueillir un artiste dans vos locaux c’est participer à son processus de création.</p>
      <p>Nos projets in situ apportent une expérience unique à vos employés de par la présence d’un artiste qui réalise l’oeuvre dans l’entreprise. Avoir la possibilité d’interagir avec un artiste qui travaille est une occasion de découvrir ce beau métier et la démarche artistique qui l’anime. Cette offre permet de prendre du recul sur votre organisation (méthodes de travail, processus internes, relation partenaires) pour repenser votre vision et redonner de l’élan à vos activités.</p>
    </div>
  </div>
  <hr>
  <div class="for-artists-section-3-atelier-ctn">
    <%= image_tag("en-atelier.jpg", alt: "en-atelier")%>
    <div class="for-artists-section-3-atelier-text-ctn">
      <h3>En <span class="span-orange">atelier</span></h3>
      <p class="p-bold">L’artiste peut également produire l’œuvre d’art dans son atelier.</p>
      <p>Il peut arriver que les locaux d’entreprises ne conviennent pas pour un projet « In-Situ » en raison de la taille des locaux ou du bruit émis par la conception de l’œuvre d’art, comme la sculpture. Dans cette offre « En atelier », nous organisons une réception dans vos locaux avec l’artiste, à nos frais, afin qu’il explique et commente son travail auprès de vos collaborateurs. Cette rencontre avec l’artiste permet de comprendre le cheminement et la réflexion qu’il a suivi pour mener à l’œuvre accomplie.</p>
    </div>
  </div>
</div>
<div class="for-artists-section-4">
  <%= link_to "Découvrez nos réalisations", artworks_path%>
  <%= link_to "Contactez-nous", "contact"%>
</div>
<script class="carousel">
  const crslNextBtn = document.querySelector('.crsl-next');
  const crslPrevBtn = document.querySelector('.crsl-prev');
  const crslAllImgs = document.querySelector('.crsl-all-img-ctn');
  const crslImgs = document.querySelectorAll('.crsl-img');
  const crslImgsLength = document.querySelectorAll('.crsl-img').length;
  var nextCount = 0;
  
  crslImgs[nextCount+1].classList.add('crsl-img-active');
  
  function crslPrevImg() {
      nextCount -= 1;
      if (nextCount < -1) {
          nextCount = crslImgsLength - 2;
      }
      crslAllImgs.style.transform = `translateX(${nextCount*50*-1}vw)`;
      if (nextCount > -1) crslImgs[nextCount].classList.remove('crsl-img-active');
      crslImgs[nextCount+1].classList.add('crsl-img-active');
      if (nextCount < crslImgsLength - 1) crslImgs[nextCount + 2].classList.remove('crsl-img-active');
  }
  function crslNextImg() {
      nextCount += 1;
      if (nextCount > crslImgsLength - 2) {
          nextCount = -1;
      }
  
      crslAllImgs.style.transform = `translateX(${nextCount*50*-1}vw)`;
      if (nextCount > -1) crslImgs[nextCount].classList.remove('crsl-img-active');
      crslImgs[nextCount+1].classList.add('crsl-img-active');
      if (nextCount < crslImgsLength - 1) crslImgs[nextCount + 2].classList.remove('crsl-img-active');
  }
  crslPrevBtn.addEventListener('click', crslPrevImg);
  crslNextBtn.addEventListener('click', crslNextImg);
</script>

app/views/statics/for_companies.html.erb
<div class="for-artists-section-1">
  <h1>Vous êtes une <span class="span-orange">entreprise</span> ?</h1>
  <div class="crsl-ctn">
    <div class="crsl-all-img-ctn">
      <div class="crsl-img-ctn">
        <%= image_tag("for-panels-7.png", alt: "art-zeppelin-index-artist-artwork", class: "crsl-img") %>
      </div>
      <div class="crsl-img-ctn">
        <%= image_tag("for-panels-4.png", alt: "art-zeppelin-index-artist-artwork", class: "crsl-img") %>
      </div>
      <div class="crsl-img-ctn">
        <%= image_tag("for-panels-5.png", alt: "art-zeppelin-index-artist-artwork", class: "crsl-img") %>
      </div>
      <div class="crsl-img-ctn">
        <%= image_tag("for-panels-6.png", alt: "art-zeppelin-index-artist-artwork", class: "crsl-img") %>
      </div>
    </div>
    <div class="crsl-controls">
      <svg class="crsl-prev" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="36" height="35" viewBox="0 0 36 35">
        <defs>
          <clipPath id="clip-Index_8">
            <rect width="36" height="35"/>
          </clipPath>
        </defs>
        <g id="Index_8" data-name="Index – 8" clip-path="url(#clip-Index_8)">
          <rect width="36" height="35" fill="#fff"/>
          <g id="Groupe_614" data-name="Groupe 614" transform="translate(-5817.75 -6010)">
            <rect id="Rectangle_228" data-name="Rectangle 228" width="36" height="35" transform="translate(5817.75 6010)" fill="#fa4616"/>
            <path id="Tracé_1157" data-name="Tracé 1157" d="M0,0,8.86,8.86,0,17.72" transform="translate(5839.361 6036.632) rotate(180)" fill="none" stroke="#fff" stroke-width="3"/>
          </g>
        </g>
      </svg>
      <svg class="crsl-next" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="36" height="35" viewBox="0 0 36 35">
        <defs>
          <clipPath id="clip-Index_9">
            <rect width="36" height="35"/>
          </clipPath>
        </defs>
        <g id="Index_9" data-name="Index – 9" clip-path="url(#clip-Index_9)">
          <rect width="36" height="35" fill="#fff"/>
          <g id="Groupe_614" data-name="Groupe 614" transform="translate(-5817.75 -6010)">
            <rect id="Rectangle_228" data-name="Rectangle 228" width="36" height="35" transform="translate(5817.75 6010)" fill="#fa4616"/>
            <path id="Tracé_1157" data-name="Tracé 1157" d="M0,0,8.86,8.86,0,17.72" transform="translate(5832.5 6018.912)" fill="none" stroke="#fff" stroke-width="3"/>
          </g>
        </g>
      </svg>
    </div>
  </div>
  <%= image_tag("img-corporate.png", alt: "art-zeppelin-index-artist-artwork-illustration")%>
</div>
<div class="section for-artists-section-2">
  <div class="for-artists-section-2-pictos-ctn">
    <div>
      <%= image_tag("icons/for-icon-5.svg", alt: "art-zeppelin-index-artist-artwork-illustration", class: "for-icons")%>
      <h3>Définition<br>
        du besoin</h3>
    </div>
    <div>
      <%= image_tag("icons/for-icon-6.svg", alt: "art-zeppelin-index-artist-artwork-illustration", class: "for-icons")%>
      <h3>Proposition de<br>
        maquettes</h3>
    </div>
    <div>
      <%= image_tag("icons/for-icon-7.svg", alt: "art-zeppelin-index-artist-artwork-illustration", class: "for-icons")%>
      <h3>Ajustements des<br>
        spécifications avec vous</h3>
    </div>
    <div>
      <%= image_tag("icons/for-icon-8.svg", alt: "art-zeppelin-index-artist-artwork-illustration", class: "for-icons")%>
      <h3>Réalisation<br>
        de l’oeuvre</h3>
    </div>
  </div>
</div>
<div class="section for-artists-section-3">
  <h2>Nos modes <span class="span-orange">opératoires</span></h2>
  <div class="for-artists-section-3-insitu-ctn">
    <%= image_tag("in-situ.jpg", alt: "in-situ")%>
    <div class="for-artists-section-3-insitu-text-ctn">
      <h3>In-<span class="span-orange">situ</span></h3>
      <p class="p-bold">Accueillir un artiste dans vos locaux c’est participer à son processus de création.</p>
      <p>Nos projets in situ apportent une expérience unique à vos employés de par la présence d’un artiste qui réalise l’oeuvre dans l’entreprise. Avoir la possibilité d’interagir avec un artiste qui travaille est une occasion de découvrir ce beau métier et la démarche artistique qui l’anime. Cette offre permet de prendre du recul sur votre organisation (méthodes de travail, processus internes, relation partenaires) pour repenser votre vision et redonner de l’élan à vos activités.</p>
    </div>
  </div>
  <hr>
  <div class="for-artists-section-3-atelier-ctn">
    <%= image_tag("en-atelier.jpg", alt: "en-atelier")%>
    <div class="for-artists-section-3-atelier-text-ctn">
      <h3>En <span class="span-orange">atelier</span></h3>
      <p class="p-bold">L’artiste peut également produire l’œuvre d’art dans son atelier.</p>
      <p>Il peut arriver que les locaux d’entreprises ne conviennent pas pour un projet « In-Situ » en raison de la taille des locaux ou du bruit émis par la conception de l’œuvre d’art, comme la sculpture. Dans cette offre « En atelier », nous organisons une réception dans vos locaux avec l’artiste, à nos frais, afin qu’il explique et commente son travail auprès de vos collaborateurs. Cette rencontre avec l’artiste permet de comprendre le cheminement et la réflexion qu’il a suivi pour mener à l’œuvre accomplie.</p>
    </div>
  </div>
</div>
<div class="for-artists-section-4">
  <%= link_to "Découvrez nos artistes", artists_path%>
  <%= link_to "Nos réalisations", artworks_path%>
  <%= link_to "Contactez-nous", "contact"%>
</div>
<script class="carousel">
  const crslNextBtn = document.querySelector('.crsl-next');
  const crslPrevBtn = document.querySelector('.crsl-prev');
  const crslAllImgs = document.querySelector('.crsl-all-img-ctn');
  const crslImgs = document.querySelectorAll('.crsl-img');
  const crslImgsLength = document.querySelectorAll('.crsl-img').length;
  var nextCount = 0;
  
  crslImgs[nextCount+1].classList.add('crsl-img-active');
  
  function crslPrevImg() {
      nextCount -= 1;
      if (nextCount < -1) {
          nextCount = crslImgsLength - 2;
      }
      crslAllImgs.style.transform = `translateX(${nextCount*50*-1}vw)`;
      if (nextCount > -1) crslImgs[nextCount].classList.remove('crsl-img-active');
      crslImgs[nextCount+1].classList.add('crsl-img-active');
      if (nextCount < crslImgsLength - 1) crslImgs[nextCount + 2].classList.remove('crsl-img-active');
  }
  function crslNextImg() {
      nextCount += 1;
      if (nextCount > crslImgsLength - 2) {
          nextCount = -1;
      }
  
      crslAllImgs.style.transform = `translateX(${nextCount*50*-1}vw)`;
      if (nextCount > -1) crslImgs[nextCount].classList.remove('crsl-img-active');
      crslImgs[nextCount+1].classList.add('crsl-img-active');
      if (nextCount < crslImgsLength - 1) crslImgs[nextCount + 2].classList.remove('crsl-img-active');
  }
  crslPrevBtn.addEventListener('click', crslPrevImg);
  crslNextBtn.addEventListener('click', crslNextImg);
</script>

app/views/statics/home.html.erb
<div class="section index-section-1">
  <div>
    <%= image_tag("index-img.png", alt: "art-zeppelin-index-illustration", class: "index-section-1-img") %>
    <div class="index-section-1-text-ctn">
      <h1>
        L'<span class="span-orange">art</span> s'invite<br>
        dans vos locaux
      </h1>
      <hr>
      <p>
        Les artistes aux savoir-faire variés conceptualisent des espaces inspirants propices au bien-être et aux échanges. <br>
        Notre double expertise, artistique et commerciale, vous accompagne de la conception à la réalisation d’œuvres d'art qui reflètent votre vision, mission et identité.<br><br>
        Nous choisissons avec un soin particulier nos artistes selon une approche prenant en compte à la fois expérience mais aussi style et technique.
      </p>
      <%= link_to( "for_companies", class: "") do %>
        offres
      <% end %>
    </div>
  </div>
</div>
<div class="section index-section-2">
  <div class="index-section-2-pictos-ctn">
    <div>
      <%= image_tag("icons/icon-1.svg", alt: "art-zeppelin-index-icon") %>
      <h3 class="">Inspirez vos équipes</h3>
    </div>
    <div>
      <%= image_tag("icons/icon-2.svg", alt: "art-zeppelin-index-icon") %>
      <h3 class="">Consolidez votre image</h3>
    </div>
    <div>
      <%= image_tag("icons/icon-3.svg", alt: "art-zeppelin-index-icon") %>
      <h3 class="">Avantages fiscaux</h3>
    </div>
  </div>
  <hr>
  <div class="index-section-2-text-ctn">
    <p>
      La présence de l’art au sein des entreprises se développe progressivement et séduit tous les secteurs, c’est un excellent moyen de transformer les espaces de façon innovante. Cultiver la notion de plaisir au travail est un moyen pertinent de créer un sentiment d’appartenance et de cohésion de groupe au sein de votre entreprise.<br>
      <br>
      Nos experts accompagnent votre réflexion stratégique lors du choix de l’artiste-auteur pour mettre en valeur votre environnement professionnel.<br>
      En effet, notre sélection d’artistes partenaires présente de multiples styles et techniques qui conviendront à l’image et aux valeurs de votre entreprise. La présence d’art contribue au maintien et au renforcement de vos relations commerciales. C’est dans un environnement accueillant et chaleureux que vos clients et partenaires se projettent, Art Zeppelin met à votre disposition l’ensemble de ses connaissances et compétences pour que cela soit chez vous, dans vos locaux. 
    </p>
    <div class="index-section-2-links-ctn">
      <%= link_to "Découvrez nos artistes", artists_path %>
      <%= link_to "Avantages fiscaux", "deductions" %>
    </div>
  </div>
</div>
<% if false %>
  <div class="section index-section-3">
    <%= link_to( "for_artists", class: "") do %>
      <h1>Vous êtes <span class="span-orange">artiste</span> ?</h1>
      <p>Venez découvrir notre démarche</p>
    <% end %>
    <%= link_to( "for_companies", class: "") do %>
      <h1>Vous représentez une <span class="span-orange">entreprise</span></h1>
      <p>Découvrez comment sublimer vos locaux avec nous</p>
    <% end %>
  </div>
<% end %>
<div class="section index-section-4">
  <h2>Ça bouge chez <span class="span-orange">Art&nbsp;Zeppelin</span></h2>
  <p class="p-bold">Inscrivez-vous à notre Newsletter pour rester au courant</p>
  <%= render 'clients/form-newsletter' %>
</div>
<div class="section index-section-5">
  <p>
    Nous partons du constat que l’art en entreprise est peu présent si ce n’est absent.<br>
    Notre équipe a pour mission de fournir un support commercial et promotionnel aux artistes afin qu’ils puissent se focaliser pleinement sur leur processus créatif.<br>
    Forte de 4 nationalités et de compétences complémentaires, Art Zeppelin une entreprise vivante et compétente pour vous conseiller dans vos choix artistiques.<br>
    Nous avons la volonté partagée de contribuer à promouvoir le travail d’artiste en France et bientôt au-delà.
  </p>
  <%= link_to image_tag("logo-bottom.png", alt: "art-zeppelin-index-icon", class: "", style: 'width: 130px; height: 130px'), 'home' %>
</div>